### ISSUE TITLE
PyCUDA ERROR: The context stack was not empty upon module cleanup

### ISSUE THREAD

**Issue by JI0726** [Xharlie/pointnerf#45]
After running  ‘bash dev_scripts/w_scannet_etf/scane241_test.sh’ and  'bash dev_scripts/w_n360/chair_test.sh' I got this PyCUDA error:
![image](https://user-images.githubusercontent.com/62940338/175032118-52d6a285-ea12-444a-82ac-e07fae03cc1e.png)
Does anybody know how to solve it?

**Comment by ZPzhu** [comment]
same problem

**Comment by hdzmtsssw** [comment]
same problem

**Comment by NUST-Machine-Intelligence-Laboratory** [comment]
similar problem, need help

**Comment by zhangchuanyi96** [comment]
similar problem, need help

**Comment by Ailon-Island** [comment]
same problem

**Comment by phillipinseoul** [comment]
same problem, has anyone found a solution?

**Comment by OvOtoQAQ** [comment]
same...

**Comment by OvOtoQAQ** [comment]
https://blog.csdn.net/Andrew_megemeta/article/details/115712499
hey guys, I find a blog which seems like be able to solve this problem, I tried a lot but still can't figure out where to pop, if anyone solve this one, please inform me.

**Comment by MobiusLqm** [comment]
Same problem!Does anyone know how to fix it??

**Comment by yjcaimeow** [comment]
try import pycuda.autoinit

**Comment by knightwzh** [comment]
Same problem

**Comment by Xharlie** [comment]
hi folks, it is wrong decision to build things in pycuda, and im sorry that i don't have enough time to rebuild everything in a fashion of pure cuda/pytorch.

**Comment by juliuskuehn1** [comment]
Hi, I have the same problem. Further I also encountered this when I was running the scripts for:
Test feed forward inference on dtu scenes like 'bash dev_scripts/dtu_test_inf/inftest_scan1.sh'. I was able to fix this by adding `model.cleanup()` and `del model` into the train_ft.py before `exit()` is called. 
Unfortunately when trying to apply this to the test_ft.py script, I run into a Segmentation fault instead of the PyCuda ERROR...

**Comment by HanLingsgjk** [comment]
> Hello, I would like to ask which parts are using pycuda. Perhaps I can rewrite these parts as cuda

**Comment by CeoiZidung** [comment]
> 

thanks, it works for me

**Comment by CTouch** [comment]
https://github.com/Xharlie/pointnerf/issues/82#issue-1643198265
Try this method.

**Comment by lhp121** [comment]
我测试代码的时候把下面的代码加在test_ft_.py最后的main函数里面了，import写在这里，不在前面的头文件那，解决了！

    if __name__ == '__main__':
        # 清除 CUDA context 栈
        import pycuda.driver as cuda
        import pycuda.autoinit
     
        cuda.Context.pop()
        main()
